import * as fs from 'node:fs'
import * as path from 'node:path'

import openapiTS, { astToString } from 'openapi-typescript'

import {
  normalizeAuthCapabilities,
  normalizeWebhookCapabilities,
} from '../packages/kanban-lite/src/shared/config'
import { resolveCapabilityBag } from '../packages/kanban-lite/src/sdk/plugins'
import {
  buildStandaloneOpenApiSpec,
  collectStandalonePluginOpenApiDocs,
} from '../packages/kanban-lite/src/standalone/internal/openapi-spec/build'

const ROOT = path.resolve(__dirname, '..')
const DOCS_KANBAN_DIR = path.join(ROOT, 'tmp', 'openapi-types-workspace', '.kanban')
const OUTPUT_FILE = path.join(
  ROOT,
  'packages',
  'kanban-lite',
  'src',
  'sdk',
  'remote',
  'generated',
  'standalone-api-paths.ts',
)

function buildSpec() {
  try {
    const capabilityBag = resolveCapabilityBag(
      {
        'card.storage': { provider: 'localfs' },
        'attachment.storage': { provider: 'localfs' },
      },
      DOCS_KANBAN_DIR,
      normalizeAuthCapabilities({
        auth: {
          'auth.identity': {
            provider: 'local',
            options: {
              apiToken: 'openapi-docs-token',
            },
          },
          'auth.policy': { provider: 'local' },
        },
      }),
      normalizeWebhookCapabilities({}),
    )

    return buildStandaloneOpenApiSpec(
      collectStandalonePluginOpenApiDocs(capabilityBag.standaloneHttpPlugins, {
        workspaceRoot: ROOT,
        kanbanDir: DOCS_KANBAN_DIR,
        capabilities: capabilityBag.providers,
        authCapabilities: capabilityBag.authProviders,
        webhookCapabilities: capabilityBag.webhookProviders,
      }),
    )
  } catch {
    return buildStandaloneOpenApiSpec()
  }
}

async function main(): Promise<void> {
  fs.mkdirSync(path.dirname(DOCS_KANBAN_DIR), { recursive: true })
  fs.mkdirSync(DOCS_KANBAN_DIR, { recursive: true })
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true })

  const spec = buildSpec()
  const ast = await openapiTS(spec as unknown as Parameters<typeof openapiTS>[0])
  const generated = astToString(ast)
  const content = [
    '/* eslint-disable */',
    '// This file is generated by `pnpm run contracts:openapi`.',
    '// Do not edit it by hand.',
    '',
    generated.trim(),
    '',
  ].join('\n')

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8')
  console.log(`Wrote ${path.relative(ROOT, OUTPUT_FILE)}`)
}

void main()
